# Backend
backend = "glx";
vsync = true;

# Transparency
active-opacity = 0.8;
inactive-opacity = 0.8;
frame-opacity = 0.9;
inactive-opacity-override = false;

opacity-rule = [
  "90:class_g = 'Alacritty'",
  "80:class_g = 'Thunar'"
];

# Shadows
shadow = true;
shadow-radius = 12;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.5;

# Corners
#round-borders = 1;

# Fading
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
